name: test

env:
  REACT_APP_VERSION: $GITHUB_RUN_ATTEMPT

on:
  push:
    branches: 
    - master

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
