name: test

env:
  REACT_APP_VERSION: $GITHUB_RUN_NUMBER

on:
  push:
    branches: 
    - master

jobs:
  build: 
    runs-on: ubuntu-latest
   
    steps:
    - name: git
      uses: actions/checkout@v2
    - name: node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: build
      env:
          ENV: dev
      run: npm ci
    - run: echo ${{ env.REACT_APP_VERSION}}
    - run: npm run build --if-present
    - run: npm run deploy

