name: test

env:
  REACT_APP_VERSION: $GITHUB_RUN_NUMBER

on:
  push:
    branches: 
    - master

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: git
      uses: actions/checkout@v2
    - name: node2
      uses: actions/setup-node@v2
    - run: npm i
    - run: echo ${{ env.REACT_APP_VERSION}}
    - run: npm run build --if-present

